name: GHA Test

on:
  workflow_dispatch:
    inputs:
      Env:
        description: Choose an environment
        required: true
        type: choice
        options:
          - prod
          - test
          - QA

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo input parameter
        run: echo "The input parameter value is: ${{ github.event.inputs.Env }}"

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Publish the application
        run: dotnet publish --configuration Release --output ./publish

      - name: Zip the publish folder
        run: zip -r publish.zip ./publish

      - name: Upload the zip file to Azure Storage
        uses: azure/cli@v1
        with:
          azcliversion: 2.59.0
          inlineScript: |
            az storage blob upload \
              --account-name teststorpras \
              --container-name teststorpras \
              --name testdotnet-${{ github.event.inputs.Env }}.zip \
              --file publish.zip \
              --auth-mode key \
              --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
